name: deepdiva
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - absl-py=0.7.1=py37_0
  - asn1crypto=0.24.0=py37_1003
  - astor=0.7.1=py_0
  - c-ares=1.15.0=h14c3975_1001
  - cffi=1.12.2=py37hf0e25f4_1
  - chardet=3.0.4=py37_1003
  - colorlog=4.0.2=py37_1000
  - cryptography=2.6.1=py37h72c5cf5_0
  - gast=0.2.2=py_0
  - h5py=2.9.0=nompi_py37hf008753_1102
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - idna=2.8=py37_1000
  - keras-applications=1.0.7=py_0
  - keras-preprocessing=1.0.9=py_0
  - libprotobuf=3.7.1=h8b12597_0
  - markdown=2.6.11=py_0
  - mock=2.0.0=py37_1001
  - pbr=5.1.3=py_0
  - protobuf=3.7.1=py37he1b5a44_0
  - pycparser=2.19=py37_1
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.6.8=py37_1002
  - python-wget=3.2=py_0
  - pyyaml=5.1=py37h14c3975_0
  - requests=2.21.0=py37_1000
  - sigopt=3.6.4=py_0
  - tensorboard=1.13.1=py37_0
  - tensorboardx=1.6=py_0
  - termcolor=1.1.0=py_2
  - tqdm=4.31.1=py_0
  - urllib3=1.24.1=py37_1000
  - werkzeug=0.15.2=py_0
  - yaml=0.1.7=h14c3975_1001
  - _tflow_select=2.3.0=mkl
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.3=199
  - ipython=7.4.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.13.3=py37_0
  - jpeg=9b=h024ee3a_2
  - keras=2.2.4=0
  - keras-base=2.2.4=py37_0
  - kiwisolver=1.0.1=py37hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - matplotlib=3.0.3=py37h5429711_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.2=py37h7e9f1db_0
  - numpy-base=1.16.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.2=py37he6710b0_0
  - parso=0.3.4=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.4.1=py37h34e0f95_0
  - pip=19.0.3=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.3.1=py37_0
  - pyparsing=2.3.1=py37_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2018.9=py37_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.3=py37hd81dba3_0
  - scipy=1.2.1=py37h7c811a0_0
  - seaborn=0.9.0=py37_0
  - setuptools=40.8.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.27.2=h7b6447c_0
  - statsmodels=0.9.0=py37h035aef0_0
  - tensorflow=1.13.1=mkl_py37h54b294f_0
  - tensorflow-base=1.13.1=mkl_py37h7ce6ba3_0
  - tensorflow-estimator=1.13.0=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.0.1=py3.7_cuda10.0.130_cudnn7.4.2_2
  - torchvision=0.2.2=py_3
  - pip:
    - rarfile==3.0
    - torch==1.0.1.post2
    - wget==3.2
prefix: /home/user/.conda/envs/deepdiva1

